### ISSUE TITLE
Changing Model CRD args should trigger graceful replace

### ISSUE THREAD

**Issue by samos123** [substratusai/kubeai#227] opened 2024-09-19 22:24 UTC
Use case:  Modify the args in a Model CRD

Expectation: A new pod is created. The old pod is deleted once new pod is reporting ready.

**Comment by nstogner** [comment] 2024-09-21 15:11
Duplicate of #219

**Comment by nstogner** [comment] 2024-09-21 15:12
Closing as duplicate

**Closed by nstogner** 2024-09-21 15:12 UTC
